name: RenpySwitch Build
run-name: ${{ github.actor }} building Ren'Py Switch 🎮
on: [push]

jobs:
    build-artifact:
        name: Build
        runs-on: ubuntu-24.04
        container: devkitpro/devkita64:20230910

        steps:
        - name: Check devkitPro environment
          run: echo $DEVKITPRO
            
        - name: Checkout repository
          uses: actions/checkout@master
          with:
            submodules: recursive
            
        - name: Fix line endings
          run: sed -i 's/\r//' setup.bash build.bash link_sources.bash

        - name: Setup environment
          run: sudo bash setup.bash
        
        - name: Build
          run: sudo bash build.bash

        - name: Upload raw artifact
          uses: actions/upload-artifact@master
          with:
            name: raw
            path: raw
